import React from 'react';import {Activity, AlertTriangle, CalendarDays, CheckCircle2, MapPin, Users, WandSparkles, CloudSun} from 'lucide-react';import {Link} from 'react-router-dom';import PageHeader from '../../components/ui/PageHeader';import StatCard from '../../components/ui/StatCard';import EventMap from '../../components/maps/EventMap';import {activeEvent} from '../../config/eventConfig';import {useEventData} from '../../context/EventDataContext';import useWeather from '../../hooks/useWeather';import hero from '../../assets/concert-hero.jpg';
export default function Dashboard(){
  const {crowd,volunteers}=useEventData();
  const {loading:weatherLoading,current:weather}=useWeather();
  const gateTone=v=>v>=85?'red':v>=70?'amber':'green';
  const busiest=Object.entries(crowd.gates).sort((a,b)=>b[1]-a[1])[0];
  return <><PageHeader eyebrow="ORGANIZER · COMMAND CENTER" title="Your event, at a glance." subtitle="Attendance, crowd, alerts and weather — everything operational in one workspace." action={<Link className="primary-btn" to="/organizer/ai-operations"><WandSparkles/> Open AI Operations</Link>}/>
  <section className="hero-card compact-hero"><img src={hero}/><div className="hero-overlay"/><div className="hero-copy"><span className="eyebrow">LIVE · 18 JAN 2026</span><h2>{activeEvent.name}</h2><p><MapPin/> {activeEvent.venue} · <Users/> {activeEvent.expectedAttendees.toLocaleString()} expected</p></div></section>
  <div className="stats-row"><StatCard icon={<Users/>} title="Live crowd" value={crowd.total.toLocaleString()} meta={`${crowd.utilization}% venue utilization`} trend/><StatCard icon={<Activity/>} title="Pressure zones" value={String(Object.values(crowd.gates).filter(v=>v>=70).length)} meta="need attention"/><StatCard icon={<MapPin/>} title={`Gate ${busiest[0]}`} value={`${busiest[1]}%`} meta={gateTone(busiest[1])==='red'?'High density':'Moderate density'}/><Link to="/organizer/weather"><StatCard icon={<CloudSun/>} title="Weather" value={weatherLoading?'—':`${weather.temp}°C`} meta={weatherLoading?'Fetching…':`${weather.description}${weather.isDemo?' · demo':''}`}/></Link></div>
  <div className="content-grid two-one"><section className="panel map-panel"><div className="panel-head"><div><h3>Live venue pulse</h3><p>Organizer-defined zones with current crowd intensity.</p></div><span className="live-pill">● LIVE</span></div><EventMap/><div className="pressure-grid">{Object.entries(crowd.gates).map(([g,v])=><div key={g}><span>Gate {g}</span><b className={gateTone(v)}>{v}%</b></div>)}</div></section>
  <section className="panel"><div className="panel-head"><div><h3><WandSparkles/> PRABANDH alerts</h3><p>Actionable signals, not noise.</p></div></div><div className="alert-item red"><AlertTriangle/><div><b>Gate {busiest[0]} is trending high</b><p>Consider redirecting attendees to a lower-pressure gate.</p></div></div><div className="alert-item green"><CheckCircle2/><div><b>Medical points staffed</b><p>All planned medical zones have coverage.</p></div></div><div className="alert-item amber"><Activity/><div><b>Food zone rising</b><p>Wait time forecast: +6 min in 20 minutes.</p></div></div></section></div></>;
}
