import React,{useState} from 'react';
import {ArrowRight,CheckCircle2,ScanLine,ShieldAlert,Users,Zap} from 'lucide-react';
import PageHeader from '../../components/ui/PageHeader';
import Badge from '../../components/ui/Badge';
import {useEventData} from '../../context/EventDataContext';
export default function Scanner(){
 const {crowd,volunteers,scanTicket,simulateSurge,pushUpdate}=useEventData();
 const [gate,setGate]=useState('B');
 const [last,setLast]=useState('CP-847291');
 const [scanFeed,setScanFeed]=useState([{id:'CP-847291',gate:'B',time:'just now'}]);
 const pressure=crowd.gates[gate]; const recommended=pressure>=85; const currentVol=volunteers.filter(v=>v.zone===`Gate ${gate}`).length;
 const scan=()=>{const id='CP-'+Math.floor(100000+Math.random()*899999);setLast(id);setScanFeed(list=>[{id,gate,time:'just now'},...list].slice(0,5));scanTicket(gate,id)};
 const surge=()=>{simulateSurge(gate);pushUpdate('Crowd surge simulated',`Gate ${gate} entry pressure increased in live operations`,'amber')};
 return <><PageHeader eyebrow="ORGANIZER · LIVE ENTRY" title="Ticket Scanner" subtitle="Every verified scan becomes a live entry event and feeds the crowd-pressure loop." action={<Badge tone={recommended?'amber':'green'}>{recommended?'HIGH PRESSURE':'NORMAL FLOW'}</Badge>}/>
 <div className="scanner-grid"><div className="panel scanner-control"><div className="panel-head"><div><h3><ScanLine/> Live entry scanner</h3><p>Verified gate activity feeds the event operations dashboard.</p></div></div><label className="scanner-label">Gate<select value={gate} onChange={e=>setGate(e.target.value)}>{Object.keys(crowd.gates).map(g=><option key={g}>{g}</option>)}</select></label><div className="scanner-frame"><ScanLine size={54}/><span>Gate {gate} live scanner</span><small>Monitoring entry flow in real time</small></div><button className="primary-btn full scan-btn" onClick={scan}><ScanLine/> SCAN TICKET</button><button className="outline-btn full" onClick={surge}><Zap/> Simulate crowd surge</button><div className="last-ticket"><span>Last Ticket</span><b>{last}</b><small><CheckCircle2/> VALID ENTRY · {scanFeed[0]?.time || 'just now'}</small></div></div>
 <div className="panel"><div className="panel-head"><div><h3>Gate pressure overview</h3><p>Live values update as scans and surges are triggered.</p></div></div><div className="gate-bars">{Object.entries(crowd.gates).map(([letter,value])=><div className="bar-row" key={letter}><b>Gate {letter}</b><div className="bar"><i style={{width:`${value}%`}}/></div><span>{value}%</span></div>)}</div><div className="scanner-stats"><div><Users/><b>{crowd.total.toLocaleString()}</b><small>Verified attendees</small></div><div><ScanLine/><b>{gate}</b><small>Active scanner</small></div><div><Zap/><b>{pressure>=85?'HIGH':'NORMAL'}</b><small>Entry velocity</small></div></div></div></div>
 <div className="content-grid two-one"><div className="panel"><div className="panel-head"><div><h3><ShieldAlert/> Operational response</h3><p>Closed-loop actions derived from the current scan pressure.</p></div></div>{recommended?<><div className="alert-card"><div className="alert-icon"><ShieldAlert/></div><div><b>Gate {gate} approaching capacity</b><small>Incoming scans are creating high entry pressure.</small></div></div><div className="action-row"><div><b>Redirect incoming attendees</b><small>Move traffic toward Gate C, currently {crowd.gates.C}%.</small></div><button className="primary-small" onClick={()=>pushUpdate('Gate redirect activated',`Attendees redirected from Gate ${gate} to Gate C`,'green')}>Redirect <ArrowRight/></button></div></>:<div className="empty-state"><CheckCircle2/><b>No intervention needed</b><span>Keep scanning. PRABANDH will surface an action when pressure rises.</span></div>}</div>
 <div className="panel"><div className="panel-head"><div><h3>Volunteer requirement</h3><p>Based on gate pressure and entry velocity.</p></div></div><div className="volunteer-reco"><div className="vol-big">{recommended?'+4':'0'}</div><div><b>{recommended?'Additional volunteers recommended':'Current coverage is sufficient'}</b><small>Gate {gate} · {currentVol} currently assigned</small></div></div><div className="action-row"><div><b>Target coverage</b><small>{recommended?'12 volunteers':'8 volunteers'} at Gate {gate}</small></div><Badge tone={recommended?'amber':'green'}>{recommended?'HIGH NEED':'COVERED'}</Badge></div></div></div></>;
}
