import React from 'react';
import {Navigate,Route,Routes} from 'react-router-dom';
import Login from './pages/auth/Login';import AppShell from './components/layout/AppShell';import RoleGuard from './components/layout/RoleGuard';
import OrganizerDashboard from './pages/organizer/Dashboard';import OrganizerCrowd from './pages/organizer/Crowd';import OrganizerVenue from './pages/organizer/Venue';import OrganizerVolunteers from './pages/organizer/Volunteers';import OrganizerAIOperations from './pages/organizer/Recommendations';import OrganizerAnalytics from './pages/organizer/Analytics';
import AttendeeHome from './pages/attendee/Home';import AttendeeMap from './pages/attendee/EventMap';import AttendeeNavigate from './pages/attendee/Navigate';import AttendeeTransport from './pages/attendee/Transport';import AttendeeSchedule from './pages/attendee/Schedule';
import OrganizerScanner from './pages/organizer/Scanner';import OrganizerTransport from './pages/organizer/Transport';
import PartnerDashboard from './pages/partner/Dashboard';import PartnerHotels from './pages/partner/Hotels';import PartnerRestaurants from './pages/partner/Restaurants';import PartnerServices from './pages/partner/Services';import PartnerRequests from './pages/partner/Requests';import PartnerProfile from './pages/partner/Profile';
import Weather from './pages/shared/Weather';
const shell=(role,element)=><RoleGuard role={role}><AppShell role={role}>{element}</AppShell></RoleGuard>;
export default function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/" element={<Navigate to="/login" replace/>}/>
<Route path="/organizer" element={shell('organizer',<OrganizerDashboard/> )}/><Route path="/organizer/crowd" element={shell('organizer',<OrganizerCrowd/> )}/><Route path="/organizer/venue" element={shell('organizer',<OrganizerVenue/> )}/><Route path="/organizer/volunteers" element={shell('organizer',<OrganizerVolunteers/> )}/><Route path="/organizer/ai-operations" element={shell('organizer',<OrganizerAIOperations/> )}/><Route path="/organizer/transport" element={shell('organizer',<OrganizerTransport/> )}/><Route path="/organizer/scanner" element={shell('organizer',<OrganizerScanner/> )}/><Route path="/organizer/weather" element={shell('organizer',<Weather role="organizer"/> )}/><Route path="/organizer/analytics" element={shell('organizer',<OrganizerAnalytics/> )}/>
<Route path="/attendee" element={shell('attendee',<AttendeeHome/> )}/><Route path="/attendee/map" element={shell('attendee',<AttendeeMap/> )}/><Route path="/attendee/navigate" element={shell('attendee',<AttendeeNavigate/> )}/><Route path="/attendee/transport" element={shell('attendee',<AttendeeTransport/> )}/><Route path="/attendee/schedule" element={shell('attendee',<AttendeeSchedule/> )}/><Route path="/attendee/weather" element={shell('attendee',<Weather role="attendee"/> )}/>
<Route path="/partner" element={shell('partner',<PartnerDashboard/> )}/><Route path="/partner/hotels" element={shell('partner',<PartnerHotels/> )}/><Route path="/partner/restaurants" element={shell('partner',<PartnerRestaurants/> )}/><Route path="/partner/services" element={shell('partner',<PartnerServices/> )}/><Route path="/partner/requests" element={shell('partner',<PartnerRequests/> )}/><Route path="/partner/profile" element={shell('partner',<PartnerProfile/> )}/><Route path="*" element={<Navigate to="/login" replace/>}/></Routes>}
